### ISSUE TITLE
Add option to add Bridges!

### ISSUE THREAD

**Issue by madixiu** [brainfucksec/archtorify#10]

**Comment by knlnlo** [comment]
It is possible that the above steps can be avoided by using the [obfs4](https://gitweb.torproject.org/pluggable-transports/obfs4.git/) package from the [AUR](https://aur.archlinux.org/packages/?O=0&SeB=nd&K=obfs4&outdated=&SB=n&SO=a&PP=50&do_Search=Go).

**Comment by brainfucksec** [comment]
Refer: https://github.com/brainfucksec/archtorify/issues/16
