### ISSUE TITLE
Allow incoming connection from LAN

### ISSUE THREAD

**Issue by solisinvictum** [brainfucksec/archtorify#12]
Hey,

first, thanks for this great script! It does exactly what i want! :-)

I have only one "issue" with that: NFS Shares arent accessable anymore from another Machine in the same lan. 

I think this is because iptables blocks everything?

**Comment by brainfucksec** [comment]
Hi @solisinvictum 
To allow internal network connections you must enter the IP address or the range of IP addresses in the iptables rules using the `ACCEPT` value in the [iptables.rules](https://github.com/brainfucksec/archtorify/blob/master/data/iptables.rules) file, e.g.:

```bash
iptables -A INPUT -s 192.168.0.178 -j ACCEPT
``` 
See: https://man.archlinux.org/man/iptables.8

This may have security implications, see: https://security.stackexchange.com/questions/189474/why-is-dhcp-considered-insecure

**Comment by solisinvictum** [comment]
Sry for the late answer!

Thanks for the Info. I give it a look. 

Could this be implemented as a option? Simply to look in what Range the Machine archtorify runs on is and then to whitelist this? --allow-lan for example or something.

**Comment by brainfucksec** [comment]
Thank you for the advice, I will consider this change.

**Comment by solisinvictum** [comment]
Thanks,

that would be really great! :)

**Comment by solisinvictum** [comment]
Im doing something wrong.

I added 

-A INPUT -s 192.168.5.0/24 -j ACCEPT

on the last position (before commit) into the file /usr/share/archtorify/data/iptables.rules

and iptables -L shows thats its active. But still cant access this machine from other machine in same lan.

-A INPUT -s 192.168.5.205 -j ACCEPT 

didnt worked too. First thought i need to create OUTPUT ones too, but that didnt helped either.

**Comment by brainfucksec** [comment]
Use the `-A` parameter:

```
-A OUTPUT -d 192.168.5.0/24 -j ACCEPT
```

See: https://www.digitalocean.com/community/tutorials/iptables-essentials-common-firewall-rules-and-commands

**Comment by solisinvictum** [comment]
Thanks for the hint.

But its still not working. I even added INPUT Rules accordingly the manuals you delivered:

![image](https://user-images.githubusercontent.com/94938946/148590213-f34f2afc-e5fe-4e40-ad90-c7934f1d9b42.png)

![image](https://user-images.githubusercontent.com/94938946/148590239-87863f49-5abd-46ae-8cc7-178c83c4bf77.png)

I give it further investigation.
