### ISSUE TITLE
Add bridges support

### ISSUE THREAD

**Issue by MbrooWs** [brainfucksec/archtorify#16]
So I thought about adding bridges support in case tor is blocked.
Here is my solution:
add `--bridges $EDITOR` parameter
then after moving torrc but before launching tor:
```
$EDITOR /tmp/bridges.txt
echo "UseBridges 1" >> /etc/tor/torrc
sed 's/^/Bridge /' /tmp/bridges.txt >> /etc/tor/torrc
rm /tmp/bridges.txt
```

**Comment by brainfucksec** [comment]
Thanks @MbrooWs, I will see how I can implement this parameter in the next updates, taking into consideration your piece of code.

**Comment by brainfucksec** [comment]
#https://github.com/brainfucksec/archtorify/issues/19

**Comment by gmankab** [comment]
hello

i am trying to use bridges, but archtorify just overwrittes the /etc/tor/torrc file with my bridges
