### ISSUE TITLE
Network does not work after returning to clearnet

### ISSUE THREAD

**Issue by HarleyQuinn-Z6** [brainfucksec/archtorify#17]
I don't know how exactly to reproduce this. Most times, when I use `sudo archtorify --tor` and later I use `sudo archtorify --clearnet` the torrent clients don't work no matter what I do (restarting, clearing the tor again, etc). Firefox also gives an error saying:

```
Hmm. We’re having trouble finding that site.

We can’t connect to the server at lemmy.ml.

If that address is correct, here are three other things you can try:

    Try again later.
    Check your network connection.
    If you are connected but behind a firewall, check that LibreWolf has permission to access the Web.
```
And there are some websites like https://forums.linuxmint.com/ that I can't visit while using tor.

**Comment by brainfucksec** [comment]
I need to know what network services you use .
If you use [dhcpcd](https://wiki.archlinux.org/title/Dhcpcd) try to restart it, same for [NetworkManager](https://wiki.archlinux.org/title/NetworkManager)

**Comment by HarleyQuinn-Z6** [comment]
It works for me after doing `sudo systemctl status NetworkManager.service` on Manjaro.

**Comment by brainfucksec** [comment]
This is a useful information, thanks.

**Comment by HarleyQuinn-Z6** [comment]
Even after restarting the network manager the torrent doesn't work. I've tried with a couple clients, with no luck. The browser does work after restarting the network manager.

**Comment by brainfucksec** [comment]
If you reboot the system everything works properl, right?

**Comment by HarleyQuinn-Z6** [comment]
> If you reboot the system everything works properly, right?
One of the times it's happened I couldn't use torrent for a few days even though I restarted multiple times.

> Can you show me the output of `cat /etc/resolv.conf` command after the stop of archtorify?
This time I entered tor `-t` and exited `-c` and then torrent worked and the browser didn't. Until I restarted the network manager.

```
cat /etc/resolv.conf
# Generated by resolvconf
```

**Comment by brainfucksec** [comment]
The `etc/resolv.conf` is empty, so you don't have the DNS servers set up.
archtorify backs up the `/etc/resolv.conf/` file at startup and restores it when finished, it seems a problem not related to archtorify but to NetworkManager.
Try these steps:

1. Uninstall `archtorify` 
2. Reboot your system
3. Check if DNS servers are defined in the file `/etc/resolv.conf`
4. Install `archtorify`

More details: [NetworkManager#DNS_management](https://wiki.archlinux.org/title/NetworkManager#DNS_management)

**Comment by HarleyQuinn-Z6** [comment]
Nevermind. I've tried reinstalling the operating system and still doesn't work so it's probably something with my network. Nothing to do with this software.

**Comment by brainfucksec** [comment]
Start from here:  https://www.redhat.com/sysadmin/beginners-guide-network-troubleshooting-linux

Then, when you have settled in you can go here: https://wiki.archlinux.org/title/Network_configuration

Try to familiarize with the key Network components of a Linux Operating System, I advice to install a Virtual Machine for testing programs like this without mess your main Operating System, about Torrent, maybe the problem is in the Router configuration, anyway I advice to use Torrents Clients with a VPN.
