### ISSUE TITLE
Add exit node selection

### ISSUE THREAD

**Issue by SKOHscripts** [brainfucksec/archtorify#18]
Hello, 
First, thank you very much for this code, that is exactly what I was looking for for a while. 

I was thinking about the possibility to select tor exit node. Whether it is temporary or not, it could be very interesting to be able to select the country of the exit node. Some contents are blocked in some countries. 
I'm not sure how to integrate this, but I know that orbot on android does it. 
Do you think you can integrate this?

**Comment by brainfucksec** [comment]
This parameter could also be inserted by editing the file `torrc`, see: https://tor.stackexchange.com/questions/733/can-i-exit-from-a-specific-country-or-node

But Tor project team advises against changing this parameter, see: [Can I pick which country I'm exiting from?](https://support.torproject.org/tbb/tbb-16/)

I suggest you to simply try with another IP address using the `--restart` command to avoid interfering with the functionality of Tor, this topic remains however object of study for me, I will make further researches.
