### ISSUE TITLE
Add options to use bridges in torrc

### ISSUE THREAD

**Issue by z36r2850o** [brainfucksec/archtorify#19]
If necessary, you can simply uncomment them, supplement them with bridge addresses, rather than look for these parameters on the network... To use it, you need to install the obfs4proxy package

```
#UseBridges 1
#ClientTransportPlugin obfs4 exec /usr/bin/obfs4proxy managed

#Bridge
#Bridge
#Bridge
...
```

**Comment by brainfucksec** [comment]
This greatly simplifies the procedure for using bridges, thank you!

**Comment by z36r2850o** [comment]
No problem.
