### ISSUE TITLE
Add pacman settings

### ISSUE THREAD

**Issue by z36r2850o** [brainfucksec/archtorify#20]
https://wiki.archlinux.org/title/Tor#Pacman

**/etc/pacman.conf**

...
XferCommand = /usr/bin/curl --socks5-hostname localhost:9050 --continue-at - --fail --output %o %u
...

It would be nice to also add .onion mirrors to **/etc/pacman.d/mirrorlist**

but I only managed to find one working...

**Comment by brainfucksec** [comment]
Hi @z36r2850o 
I really believe that archtorify should not interfere with the `pacman.conf` file, but I can put this instruction in the Wiki, thanks for your advice.

As far as I know there are no .onion mirrors for Arch Linux: https://archlinux.org/mirrors/status/
Maybe I'm wrong?

**Comment by z36r2850o** [comment]
>I really believe that archtorify should not interfere with the pacman.conf

May I know why you think so?

> Maybe I'm wrong?

And no, you won't find .onion mirrors on there. I'll leave links to them, but I must admit that they are unstable, so you shouldn't use them...

https://sergal.org/mirror/
https://www.boerm.me/services/

**Comment by brainfucksec** [comment]
> May I know why you think so?

archtorify was born as a "clone" or mirror program of kalitorify, whose initial project was to create a KISS version of other similar scripts, eliminating everything that I considered unnecessary in such a program (like changing the mac address, or clean up the ram etc.), I believe that this must remain the basis of these programs.
Arch users know (or should know) how to modify pacman and update the system with or without Tor, without resorting to an automatic script.

> And no, you won't find .onion mirrors on there. I'll leave links to them, but I must admit that they are unstable, so you shouldn't use them...

I see that they are official mirrors anyway, thank you for pointing them out, as mentioned above I will post instructions in the Wiki.

**Comment by z36r2850o** [comment]
>Arch users know (or should know) how to modify pacman and update the system with or without Tor, without resorting to an automatic script.

The same applies to the entire Tor setup. But this does not mean that all these actions, in the presence of such a wonderful tool as archtorify, must be carried out manually every time.

**Comment by brainfucksec** [comment]
Reasonable, I will take this parameter into consideration for future updates.
