### ISSUE TITLE
Tor not working properly

### ISSUE THREAD

**Issue by z0x00** [brainfucksec/archtorify#24]
**Describe the bug**
Tor not working properly and is very slow to the point that it is unusable.

**Program error message**
Your system is not using Tor!
and on restart `archtorify --restart` -> `https://ipapi.co/json/` returns nothing though tor is running.

**Comment by brainfucksec** [comment]
I pushed the update now, please update to the latest version.
See: [v1.30.1 - 2022-05-31](https://github.com/brainfucksec/archtorify/commit/cb09409c9b507f9dd240c35b9927d60b02bc0b5e).
