### ISSUE TITLE
Changing default torrc config

### ISSUE THREAD

**Issue by Jeidnx** [brainfucksec/archtorify#28]
After using this script the torrc on my system states to not edit this file, and references the README. I couldn't find anything regarding this in the README. How would one go about changing the torrc, without the changes getting overwritten?

**Comment by brainfucksec** [comment]
Hi @Jeidnx I don't think I understand what your need.
Do you need to make any additional changes to the torrc file before running the program?

**Comment by Jeidnx** [comment]
I want to change global tor settings - like specify entry or exit nodes - without them getting overwritten every time i run the script.
One possible solution would be to clarify in the README that this is not possible. Currently the [torrc](https://github.com/brainfucksec/archtorify/blob/master/data/torrc) Links to the README, where no mention is made of the torrc file.

I am not totally familiar with which settings this script needs to overwrite. The only way i can think of right now to implement this, without having to parse the config file and only change necessary settings, is adding some sort of overwrites file, which the script automatically appends at the end of the torrc.

**Comment by brainfucksec** [comment]
You can add the parameters you need in the `torrc` file of archtorify before run the program.
