### ISSUE TITLE
Adding torsocks to only torify one application without the whole system

### ISSUE THREAD

**Issue by LikDev-256** [brainfucksec/archtorify#29]
When the above script is called it pipes all the system traffic through tor but I would like a feature to just run one command or application through tor.

**Comment by brainfucksec** [comment]
Well, as you have already indicated, you can just use [torsocks](https://linux.die.net/man/1/torsocks).
There is no reason I think to integrate it into archtorify, it would be a useless abstraction, they are two separate scripts for different purposes it seems fair to me to leave things as they are.
