### ISSUE TITLE
IP Rotator Request

### ISSUE THREAD

**Issue by AlwaysLivid** [brainfucksec/archtorify#3]
This isn't really a bug, but I still decided to make this issue, since this would probably be a useful/interesting feature.

Could you add support for automated IP rotating? That would be beneficial to some, particularly because the indiscriminate routing of traffic of an entire system could lead to the identification of a user.

**Comment by AlwaysLivid** [comment]
I could also attempt to work on this (since implementing this would work similarly to typing `archtorify --tor` or `archtorify --restart` repeatedly), but I'm not quite sure whether I should do that, in all honesty.

**Comment by brainfucksec** [comment]
Hi @AlwaysLivid.
I've taken delivery of the request, we'll see in the next updates. Thank you for your interest and report.
