### ISSUE TITLE
Starting the program kills ufw service

### ISSUE THREAD

**Issue by n3rd0n3** [brainfucksec/archtorify#31]
**Describe the bug**

**Program error message**
The error message returned by the program.

**Screenshots**

**Other network proxies/firewalls or DNS applications installed**
[e.g. firewalld, UFW, DNSCrypt]

**Shell used**
[e.g. bash, zsh, ksh]

**Additional context**

**Comment by brainfucksec** [comment]
You need to disable `ufw` before start the program.
See: [README - Usage](https://github.com/brainfucksec/kalitorify/blob/master/README.md#usage)
