### ISSUE TITLE
archtorify breaks virtualization

### ISSUE THREAD

**Issue by AlwaysLivid** [brainfucksec/archtorify#4]
**Describe the bug**
Using Archtorify seems to break bridged networks, which essentially bars the ability to access external resources from a virtual machine.

**Program error message**
The program and virt-manager do not return an error message and the virtual networks are activated as well.

**Other network proxies/firewalls or DNS applications installed**
* firewalld

**Shell used**
* zsh

**Additional context**
Creating a virtual machine with virt-manager, enabling `archtorify` and using the default configurations for creating a bridged network (NAT) should be enough to reproduce this issue.

**Comment by AlwaysLivid** [comment]
*Just in case* any issues with reproducing the issue arise due to the networking configurations, here's a [tutorial](https://blog.programster.org/kvm-missing-default-network).

**Comment by brainfucksec** [comment]
Hi @AlwaysLivid  thank you for the report, I'll take charge of the problem.

**Comment by AlwaysLivid** [comment]
> Hi @AlwaysLivid thank you for the report, I'll take charge of the problem, however, the information is not enough to reproduce the problem.
> Bridged Network and NAT aren't the same thing, you run `archtorify` on the `host`?
> Virtual machine tests are performed with VirtualBox so I cannot guarantee support for other platforms.

Oops, sorry for not clarifying. But yeah, I did run `archtorify` on my host machine. In my case, I was using `virt-manager` rather than VirtualBox.

You could replicate my own settings by following [the tutorial that I contributed to for the Haiku operating system](https://www.haiku-os.org/guides/virtualizing/kvm) (which is what I'm currently emulating, however, this should be guest OS-agnostic) with another operating system. I'm just linking it because those are the settings that I am currently using myself.

**Comment by brainfucksec** [comment]
Thanks for the information, to give you a comprehensive answer, I need to better understand how the network works on KVM.

**Comment by brainfucksec** [comment]
Since it’s been one month, I hope things are working well for you
now. I’ll close the issue until we can confirm it’s still happening. I’m
happy to continue further discussion whenever needed.
