### ISSUE TITLE
Arch torify check status shouldn't require root

### ISSUE THREAD

**Issue by ccxex29** [brainfucksec/archtorify#5]
`archtorify -s` or `archtorify --status` goes to `check_status` function.

At the top of the function, `check_root` function is called, so the program complains if it isn't run as root. However, I didn't find any need for root access to check, as `systemctl is-active tor.service` doesn't require root access. I needed archtorify to run on my script which shouldn't be run on root, so I think you can remove `check_root` in `check_status` if you think that's OK.

**Comment by brainfucksec** [comment]
Hi @ccxex29, thanks for the report.
In fact, I think that the check root in that function is pretty useless, I will modify the function as soon as possible.
For now, if you need, just comment the following line of code:

https://github.com/brainfucksec/archtorify/blob/master/archtorify.sh#L289

**Comment by brainfucksec** [comment]
Code changed, see the last update and/or commit.
Thanks for the help.
