### ISSUE TITLE
SSH and apache 

### ISSUE THREAD

**Issue by se7en-x230** [brainfucksec/archtorify#7]
I have a noip account but if the tor service is running I am unable to connect to SSH or my apache

**Comment by brainfucksec** [comment]
Hi @se7en-x230, The report is unclear, more details are needed for a support.
Probably is a DNS port problem but with these few details I can't help you.

**Comment by se7en-x230** [comment]
Thanks for the response.

As soon as I start  archtorify I can't reach the computer via ssh or the webserver running anymore.

I use noip service to reach the computer via a fix name.
ssh user@something.ddns.net is not possible anymore.

I have to return to clearnet to be able to connect.

My work around for now is I run xautolock -t 5 -lock script.sh (archtorify -c  ;slock)
And another that checks if slock is active and if not it will start archtorify again.

Meaning I can use ssh when the computer is locked.

**Comment by brainfucksec** [comment]
Ok, Ok, the problem should be due to the iptables rules, I have not included the rule regarding SSH, I will work to implement it in the next version.
For now you can see an example here:

https://gitlab.torproject.org/legacy/trac/-/wikis/doc/TransparentProxy

see:
```bash
### *filter INPUT
# Don't forget to grant yourself ssh access from remote machines before the DROP.
#iptables -A INPUT -i $_out_if -p tcp --dport 22 -m state --state NEW -j ACCEPT

```

**Comment by se7en-x230** [comment]
Exellent thanks for the help.
