### ISSUE TITLE
Internet connection breaks after clearnet command

### ISSUE THREAD

**Issue by Singh-00** [brainfucksec/archtorify#8]
**Describe the bug**
After using archtorify if i use the clearnet command my device is not able to connect to internet but then i use archtorify --tor command to start the service internet works or else i have to restart the device  
**Program error message**
Search engine is unable to find dns address

**Other network proxies/firewalls or DNS applications installed**
Firewall is on 

**Shell used**
bash

**Comment by brainfucksec** [comment]
Hi @Singh-00, thanks for the advice.
Try to uninstall/reinstall program for upgrade to the latest version.
