### ISSUE TITLE
Add the ability to choose between iptables and nftables

### ISSUE THREAD

**Issue by knlnlo** [brainfucksec/archtorify#9]

**Comment by brainfucksec** [comment]
Hi @knlnlo, this is already on my TODOs, but I think that for this I need to rewrite an entire new script only for nftables.

**Comment by knlnlo** [comment]
This is redundant, you can edit the existing one by adding a simple if/then construct.

**Comment by brainfucksec** [comment]
Thank you for the advic, anyway you can fork this repository and make the changes you are interested in, this is the purpose of GitHub.

**Comment by z36r2850o** [comment]
Please do it!
